[project]
name = "fuckzhs-master"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=2.7.2",
    "pillow>=8.1.1",
    "pycryptodome>=3.23.0",
    "requests>=2.32.5",
    "tiktoken>=0.12.0",
]
